import { chromium } from 'playwright';
const b = await chromium.launch({ executablePath:'/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary', headless:false, args:['--enable-unsafe-webgpu','--enable-features=WebGPU','--use-angle=metal','--no-first-run'] });
const p = await b.newPage();
p.on('console', m=>{const t=m.text(); if(/done:|ERROR|GPUERR/.test(t)) console.log('MEAS', t.slice(0,200));});
await p.goto('http://localhost:8013/index.html', { waitUntil:'domcontentloaded' });
await p.click('#load');
const wait=async(pred,max)=>{const t0=Date.now();while(Date.now()-t0<max){const s=await p.$eval('#status',e=>e.textContent);if(pred(s))return s;await p.waitForTimeout(1500);}throw new Error('timeout: '+await p.$eval('#status',e=>e.textContent));};
await wait(s=>s.startsWith('READY'),180000);
await p.click('#go');
const s=await wait(s=>s.startsWith('done'),200000);
console.log('MEAS', s);
await b.close();
