import { PreTrainedTokenizer } from '@huggingface/transformers';
import fs from 'fs';
const tj = JSON.parse(fs.readFileSync('model/tokenizer.json'));
const tc = JSON.parse(fs.readFileSync('model/tokenizer_config.json'));
const tok = new PreTrainedTokenizer(tj, tc);
const prompt = "<|im_start|>system\nYou are helpful.<|im_end|>\n<|im_start|>user\nHi<|im_end|>\n<|im_start|>assistant\n";
const ids = tok.encode(prompt);
console.log('prompt ids first12:', ids.slice(0,12));
console.log('len', ids.length);
console.log('im_start=', tok.encode("<|im_start|>"), 'im_end=', tok.encode("<|im_end|>"), 'endoftext=', tok.encode("<|endoftext|>"));
console.log('decode roundtrip:', JSON.stringify(tok.decode(ids).slice(0,90)));
console.log('encode "Hello world":', tok.encode("Hello world"), '-> decode:', JSON.stringify(tok.decode(tok.encode("Hello world"))));
